// export const SIGNUP_REQUEST = 'SIGNUP_REQUEST'
// export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
// export const SIGNUP_FAILURE = 'SIGNUP_FAILURE'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const GET_HELLO_REQUEST = 'GET_HELLO_REQUEST'
export const GET_HELLO_SUCCESS = 'GET_HELLO_SUCCESS'
export const GET_HELLO_FAILURE = 'GET_HELLO_FAILURE'

export const GET_LOGOUT_REQUEST = 'GET_LOGOUT_REQUEST'
export const GET_LOGOUT_SUCCESS = 'GET_LOGOUT_SUCCESS'
export const GET_LOGOUT_FAILURE = 'GET_LOGOUT_FAILURE'
